-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 23:05:21 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 1st_sem2_final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 1st_sem2_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `1st_sem2_final` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `1st_sem2_final` ;

-- -----------------------------------------------------
-- Table `1st_sem2_final`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1st_sem2_final`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `1st_sem2_final`.`delivery_arrive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1st_sem2_final`.`delivery_arrive` (
  `Batch_id` INT NOT NULL,
  `crate_id` INT NOT NULL,
  `Arrival_date` DATE NOT NULL,
  `Quantities` INT NOT NULL,
  PRIMARY KEY (`Batch_id`, `Arrival_date`, `crate_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `1st_sem2_final`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1st_sem2_final`.`employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `1st_sem2_final`.`sorted_batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1st_sem2_final`.`sorted_batch` (
  `sorted_id` INT NOT NULL AUTO_INCREMENT,
  `delivery_arrive_Batch_id` INT NOT NULL,
  `category_category_id` INT NOT NULL,
  `Item_name` VARCHAR(45) NOT NULL,
  `Quantities` INT NOT NULL,
  `delivery_arrive_crate_id` INT NOT NULL,
  `delivery_arrive_Arrival_date` DATE NOT NULL,
  PRIMARY KEY (`sorted_id`),
  INDEX `fk_Sorted_batch_category1_idx` (`category_category_id` ASC) VISIBLE,
  INDEX `fk_sorted_batch_delivery_arrive1_idx` (`delivery_arrive_Batch_id` ASC, `delivery_arrive_Arrival_date` ASC, `delivery_arrive_crate_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sorted_batch_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `1st_sem2_final`.`category` (`category_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_sorted_batch_delivery_arrive1`
    FOREIGN KEY (`delivery_arrive_Batch_id` , `delivery_arrive_Arrival_date` , `delivery_arrive_crate_id`)
    REFERENCES `1st_sem2_final`.`delivery_arrive` (`Batch_id` , `Arrival_date` , `crate_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `1st_sem2_final`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1st_sem2_final`.`items` (
  `items_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `Sorted_batch_sorted_id` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`items_id`),
  INDEX `fk_items_Sorted_batch1_idx` (`Sorted_batch_sorted_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_Sorted_batch1`
    FOREIGN KEY (`Sorted_batch_sorted_id`)
    REFERENCES `1st_sem2_final`.`sorted_batch` (`sorted_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
