/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pkg1st_sem2_final_fixed;

import java.sql.Connection;

/**
 *
 * @author river
 */
public class pricing_inventory extends javax.swing.JDialog {

    /**
     * Creates new form pricing_inventory
     */
    public pricing_inventory(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refreshPricingUI();
        refreshInventoryTable("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(720, 480));
        jPanel2.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(3).setResizable(false);
            jTable3.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel8.add(jScrollPane3);
        jScrollPane3.setBounds(1, 45, 658, 378);

        jTextField4.setBackground(new java.awt.Color(204, 204, 255));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField4);
        jTextField4.setBounds(90, 10, 110, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SEARCH:");
        jPanel8.add(jLabel1);
        jLabel1.setBounds(24, 12, 70, 22);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(30, 40, 660, 410);

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(630, 0, 79, 27);

        getContentPane().add(jPanel2, "card3");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 480));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 30, 320, 210);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(30, 250, 660, 200);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(360, 30, 330, 100);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(360, 140, 160, 100);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(640, 0, 60, 27);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField3.setText("jTextField3");

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(530, 140, 160, 100);

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Method to populate jTable3
    private void refreshInventoryTable(String searchTerm) {
        javax.swing.table.DefaultTableModel model3 = (javax.swing.table.DefaultTableModel) jTable3.getModel();
        model3.setRowCount(0); // Clear the table before loading new search results
        
        CRUD_OP crud = new CRUD_OP();
        java.sql.ResultSet rs = crud.searchInventory(searchTerm);
          
        if (rs != null) {
            try {
                while (rs.next()) {
                    // Make sure your jTable3 columns match this order in the Design view!
                    model3.addRow(new Object[]{
                        rs.getInt("items_id"),
                        rs.getString("code"),
                        rs.getString("Item_name"), // This successfully displays the NAME!
                        rs.getDouble("price"),
                        rs.getString("Status")
                    });
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    public void showSpecificCard(String cardName) {
        java.awt.Container contentPane = this.getContentPane();
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) contentPane.getLayout();
        cardLayout.show(contentPane, cardName);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTextField1.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Warning: Price cannot be empty!");
            return;
        }

        double inputPrice;
        try {
            inputPrice = Double.parseDouble(jTextField1.getText().trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Warning: Price must be a valid number!");
            return;
        }

        try {
            java.sql.Connection conn = DBConnection.getConnection();

            // 2. Determine Mode based on JComboBox being locked or unlocked
            if (jComboBox1.isEnabled()) {

                if (jComboBox1.getSelectedItem() == null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Warning: No batch selected to price!");
                    return;
                }

                // Get hidden data from the combobox item
                BatchComboItem selectedBatch = (BatchComboItem) jComboBox1.getSelectedItem();

                // Format the Smart Code: Batch_id - MMDDYY - crate_id
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMddyy");
                String formattedDate = sdf.format(selectedBatch.arrivalDate);
                String smartCode = selectedBatch.batchId + "-" + formattedDate + "-" + selectedBatch.crateId;

                // Pack the data into your ItemsInfo Model!
                // Note: itemsId is set to 0 because the database will Auto-Increment it.
                ItemsInfo newItem = new ItemsInfo(0, smartCode, selectedBatch.sortedId, inputPrice, "Available");

                // Insert into Database
                String insertSql = "INSERT INTO 1st_sem2_final.items (code, Sorted_batch_sorted_id, price, Status) VALUES (?, ?, ?, ?)";
                java.sql.PreparedStatement pstmt = conn.prepareStatement(insertSql);
                pstmt.setString(1, newItem.getCode());
                pstmt.setInt(2, newItem.getSortedBatchId());
                pstmt.setDouble(3, newItem.getPrice());
                pstmt.setString(4, newItem.getStatus());

                pstmt.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Successfully Priced! Smart Code Generated: " + smartCode);

            } else {

                int updateId = Integer.parseInt(jTextField2.getText().trim());

                String updateSql = "UPDATE 1st_sem2_final.items SET price = ? WHERE items_id = ?";
                java.sql.PreparedStatement pstmt = conn.prepareStatement(updateSql);
                pstmt.setDouble(1, inputPrice);
                pstmt.setInt(2, updateId);

                pstmt.executeUpdate();

                // Unlock UI and clear fields after successful update
                jComboBox1.setEnabled(true);
                jTextField2.setText("");
                javax.swing.JOptionPane.showMessageDialog(this, "Price Updated Successfully!");
            }

            // 3. Reset Fields and Refresh Tables
            jTextField1.setText("");
            refreshPricingUI(); // Reloads both tables to reflect the new state

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            int updateId = Integer.parseInt(jTextField2.getText().trim());
            java.sql.Connection conn = DBConnection.getConnection();

            // Check if item exists and fetch its current data 
            String checkSql = "SELECT i.price, sb.Item_name "
                    + "FROM 1st_sem2_final.items i JOIN 1st_sem2_final.sorted_batch sb ON i.Sorted_batch_sorted_id = sb.sorted_id "
                    + "WHERE i.items_id = ?";

            java.sql.PreparedStatement pstmt = conn.prepareStatement(checkSql);
            pstmt.setInt(1, updateId);
            java.sql.ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                // Success! Item found. Lock the UI into "Update Mode"
                jComboBox1.removeAllItems(); // Clear it
                jComboBox1.addItem(rs.getString("Item_name")); // Just show the raw name
                jComboBox1.setEnabled(false); // Lock the combobox!

                jTextField1.setText(String.valueOf(rs.getDouble("price"))); // Show old price
                javax.swing.JOptionPane.showMessageDialog(this, "Item found. Enter new price and click Save/Update.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Warning: Item ID not found in database.");
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Warning: Please enter a valid numerical Item ID.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String inputId = jTextField3.getText().trim();
    if (inputId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Warning: Please enter a Sorted ID to delete.");
        return;
    }

    int sortedIdToDelete;
    try {
        sortedIdToDelete = Integer.parseInt(inputId);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Warning: The Sorted ID must be a valid number.");
        return;
    }

    // 2. Confirmation Dialog
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Are you absolutely sure you want to delete Sorted ID: " + sortedIdToDelete + "?\nThis action cannot be undone.", 
        "Confirm Deletion", 
        javax.swing.JOptionPane.YES_NO_OPTION, 
        javax.swing.JOptionPane.WARNING_MESSAGE);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        
        // 3. USE YOUR ItemsInfo MODEL!
        // We only need to pass the sortedIdToDelete, so we can leave the other fields blank/zero
        ItemsInfo itemCarrier = new ItemsInfo(0, "", sortedIdToDelete, 0.0, "");
        
        // 4. USE YOUR CRUD_OP CLASS!
        CRUD_OP crudOps = new CRUD_OP();
        boolean success = crudOps.deleteBatchUsingItemInfo(itemCarrier);

        // 5. Update the UI based on the result
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Batch successfully deleted!");
            jTextField3.setText(""); // Clear the text field
            refreshPricingUI();      // Refresh jTable1 immediately!
        } else {
            // Only show this if they typed an ID that doesn't exist
            // (The SQL error popup is handled directly inside CRUD_OP now)
            javax.swing.JOptionPane.showMessageDialog(this, "Deletion failed or ID not found.");
        }
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        String searchText = jTextField4.getText().trim();
        refreshInventoryTable(searchText);
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    public class BatchComboItem {

        public int sortedId;
        public String itemName;
        public int batchId;
        public int crateId;
        public java.sql.Date arrivalDate;

        public BatchComboItem(int sortedId, String itemName, int batchId, int crateId, java.sql.Date arrivalDate) {
            this.sortedId = sortedId;
            this.itemName = itemName;
            this.batchId = batchId;
            this.crateId = crateId;
            this.arrivalDate = arrivalDate;
        }

        @Override
        public String toString() {
            return itemName; // This is what the user actually sees in the dropdown
        }
    }

    public void refreshPricingUI() {
        javax.swing.table.DefaultTableModel model1 = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        javax.swing.table.DefaultTableModel model2 = (javax.swing.table.DefaultTableModel) jTable2.getModel();
        model1.setRowCount(0);
        model2.setRowCount(0);
        jComboBox1.removeAllItems();

        try {
            Connection conn = DBConnection.getConnection();

            // 1. Load Unpriced Batches (jTable1 and jComboBox1)
            // We join sorted_batch and delivery_arrive to get the dates and crate IDs for the Smart Code
            // 1. Load Unpriced Batches (jTable1 and jComboBox1) using a safe LEFT JOIN
            String unpricedSql = "SELECT sb.sorted_id, sb.Item_name, sb.Quantities, da.Batch_id, da.crate_id, da.Arrival_date "
                    + "FROM 1st_sem2_final.sorted_batch sb "
                    + "LEFT JOIN 1st_sem2_final.delivery_arrive da ON sb.delivery_arrive_Batch_id = da.Batch_id "
                    + "WHERE NOT EXISTS (SELECT 1 FROM 1st_sem2_final.items i WHERE i.Sorted_batch_sorted_id = sb.sorted_id)";

            java.sql.PreparedStatement pstmt1 = conn.prepareStatement(unpricedSql);
            java.sql.ResultSet rs1 = pstmt1.executeQuery();

            while (rs1.next()) {
                // Add to jTable1 (Only Name and Quantity)
                System.out.println("Found unpriced item: " + rs1.getString("Item_name"));
                model1.addRow(new Object[]{rs1.getString("Item_name"), rs1.getInt("Quantities")});

                // Add to jComboBox1 (Using our helper class to store hidden data)
                ((javax.swing.JComboBox) jComboBox1).addItem(new BatchComboItem(
                        rs1.getInt("sorted_id"), rs1.getString("Item_name"),
                        rs1.getInt("Batch_id"), rs1.getInt("crate_id"), rs1.getDate("Arrival_date")
                ));

            }

            // 2. Load Priced Items (jTable2) - Displaying Name instead of ID
            String pricedSql = "SELECT i.items_id, i.code, sb.Item_name, i.price, i.Status "
                    + "FROM 1st_sem2_final.items i "
                    + "JOIN 1st_sem2_final.sorted_batch sb ON i.Sorted_batch_sorted_id = sb.sorted_id";

            java.sql.PreparedStatement pstmt2 = conn.prepareStatement(pricedSql);
            java.sql.ResultSet rs2 = pstmt2.executeQuery();

            while (rs2.next()) {
                model2.addRow(new Object[]{
                    rs2.getInt("items_id"), rs2.getString("code"),
                    rs2.getString("Item_name"), rs2.getDouble("price"), rs2.getString("Status")
                });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pricing_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pricing_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pricing_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pricing_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pricing_inventory dialog = new pricing_inventory(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
